<?php
/**
 * Trendyol Production Configuration
 * Auto-generated by deployment script
 * Date: $(date)
 */

// Production API Configuration
define('TRENDYOL_API_URL', 'https://api.trendyol.com');
define('TRENDYOL_WEBHOOK_ENDPOINT', 'https://your-domain.com/trendyol_webhook');
define('TRENDYOL_ENVIRONMENT', 'PRODUCTION');

// Production Settings
$config['trendyol_active'] = true;
$config['webhook_enabled'] = true;
$config['real_time_sync'] = true;
$config['campaign_management'] = true;
$config['order_processing'] = true;
$config['inventory_sync'] = true;

// Performance Settings
$config['api_timeout'] = 30;
$config['webhook_timeout'] = 60;
$config['batch_size'] = 100;
$config['sync_interval'] = 300; // 5 minutes

// Security Settings
$config['api_rate_limit'] = 1000; // requests per minute
$config['webhook_verification'] = true;
$config['ssl_verify'] = true;

// Monitoring Settings
$config['enable_logging'] = true;
$config['log_level'] = 'INFO';
$config['alert_on_errors'] = true;
$config['performance_monitoring'] = true;

echo "✅ Trendyol Production Configuration Active";
?>
